### ISSUE TITLE
Cancel Button Redirection Not Working

### ISSUE THREAD

**Issue by BhagyaRana** [BhagyaRana/LoanSwiftPro#68]

**Comment by Puttaraja** [comment]
On cancelling in which component and where to redirect.?

**Comment by BhagyaRana** [comment]
Depends on Cancel Button, But it should direct to home Page of Respective Form
For Example, Cancel Button of Register should redirect to Home Page Containing the Button to Register and so on.

**Comment by BhagyaRana** [comment]
Fixed
