### ISSUE TITLE
Delete Active Loan Issue

### ISSUE THREAD

**Issue by BhagyaRana** [BhagyaRana/LoanSwiftPro#71]
Check the Condition that curr_date > return_date
Admin will delete the Loan which are not currently active
Filter Criteria  while Fetching

**Comment by Puttaraja** [comment]
Return date will always be greater than current date. For loan type there is no return date.

**Comment by Puttaraja** [comment]
Can you elaborate this one clearly with use case scenario

**Comment by Puttaraja** [comment]
Admin can delete any loans not only active or inactive

**Comment by BhagyaRana** [comment]
Actually Mam said that Admin should be Able to delete only those Loan where
return_date (i.e. issue_date [25-Sept-2021] + duration_of_loan [2 Years]) [Eg - 25-Sept-2023] < current_date (29-Sept-2023)
Admin should not be able to delete those Loans which are currently active. (i.e. whose return_date >= current_date)

**Comment by BhagyaRana** [comment]
Fixed
