### ISSUE TITLE
Code Refactor

### ISSUE THREAD

**Issue by BhagyaRana** [BhagyaRana/LoanSwiftPro#75]
- Remove All Unnecessary Packages (Ctrl + Shift + O)
- Format the Back end Code  (Ctrl + Shift + F)
- Rename Package Name - lowercase
- Rename Class Name - Capital Case
- Rename Method Name - CamelCase

**Comment by Puttaraja** [comment]
Backend and frontend code cleaning is done, and variable names are fine

**Comment by BhagyaRana** [comment]
#89 Addressed this Issue for Backend
