### ISSUE TITLE
Future Enhancements

### ISSUE THREAD

**Issue by BhagyaRana** [BhagyaRana/LoanSwiftPro#77]
- We are Currently just applying for Loan and not Calculating the Financing Aspects like EMI
- Payments is Not Integrated
- Password are Not Stored in Encrypted Form (Spring Security)

**Comment by Puttaraja** [comment]
- There are some missing relationships in the entities Like Loan type and Item category should have one to one relationship and also employee issue id and employee card id should have one to one relationship.

**Comment by BhagyaRana** [comment]
#113 Added in Presentation
